"""init

Revision ID: 1213c329a4bc
Revises: None
Create Date: 2016-11-23 20:44:54.788001

"""

# revision identifiers, used by Alembic.
revision = '1213c329a4bc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index('ix_posts_timestamp', 'posts', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_timestamp', 'posts')
    op.drop_column('posts', 'timestamp')
    ### end Alembic commands ###
