"""empty message

Revision ID: 2315d299ea41
Revises: 1213c329a4bc
Create Date: 2016-11-23 20:50:02.640327

"""

# revision identifiers, used by Alembic.
revision = '2315d299ea41'
down_revision = '1213c329a4bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('file_img', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'file_img')
    ### end Alembic commands ###
