"""empty message

Revision ID: 42df74c64f13
Revises: e378d7a5bce
Create Date: 2016-11-28 21:36:44.399014

"""

# revision identifiers, used by Alembic.
revision = '42df74c64f13'
down_revision = 'e378d7a5bce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('blog_comment', sa.Text(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'posts', 'comment')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'posts', sa.Column('comment', sa.TEXT(), nullable=True))
    op.drop_table('comment')
    ### end Alembic commands ###
