"""empty message

Revision ID: 445c49bdfc9d
Revises: None
Create Date: 2016-11-22 22:48:46.750625

"""

# revision identifiers, used by Alembic.
revision = '445c49bdfc9d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('abstract', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('tags', sa.String(), nullable=True))
    op.drop_column('posts', 'timestamp')
    op.drop_index('ix_posts_timestamp', 'posts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_timestamp', 'posts', ['timestamp'], unique=False)
    op.add_column('posts', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_column('posts', 'tags')
    op.drop_column('posts', 'abstract')
    ### end Alembic commands ###
