"""empty message

Revision ID: 48acd4b2e4db
Revises: 2315d299ea41
Create Date: 2016-11-23 20:52:05.638930

"""

# revision identifiers, used by Alembic.
revision = '48acd4b2e4db'
down_revision = '2315d299ea41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
