"""empty message

Revision ID: 536ac5270ab8
Revises: 48acd4b2e4db
Create Date: 2016-11-23 21:18:50.335552

"""

# revision identifiers, used by Alembic.
revision = '536ac5270ab8'
down_revision = '48acd4b2e4db'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
