"""empty message

Revision ID: e378d7a5bce
Revises: 536ac5270ab8
Create Date: 2016-11-28 20:55:54.758186

"""

# revision identifiers, used by Alembic.
revision = 'e378d7a5bce'
down_revision = '536ac5270ab8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comment', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'comment')
    ### end Alembic commands ###
